(() => {
  'use strict';
  const CFG=window.APP_CONFIG||{},SB=CFG.SUPABASE_URL,KEY=CFG.SUPABASE_PUBLISHABLE_KEY,$=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function session(){try{return JSON.parse(localStorage.getItem('vendor_order_session')||'null')}catch{return null}}
  function jwt(token=''){try{const p=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'),pad=p.length%4?'='.repeat(4-p.length%4):'';return JSON.parse(decodeURIComponent(escape(atob(p+pad))))}catch{return {}}}
  function role(){return jwt(session()?.access_token||'').app_metadata?.role||''}
  async function rest(path){const s=session();if(!s?.access_token)throw new Error('登入已過期');const r=await fetch(`${SB}/rest/v1/${path}`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
  function header(bodyId,after){const table=$(bodyId)?.closest('table'),tr=table?.querySelector('thead tr');if(!tr||[...tr.children].some(x=>x.textContent.trim()==='出貨箱數'))return;const cells=[...tr.children],idx=cells.findIndex(x=>x.textContent.trim()===after),th=document.createElement('th');th.textContent='出貨箱數';if(idx>=0&&cells[idx].nextSibling)tr.insertBefore(th,cells[idx].nextSibling);else tr.appendChild(th)}
  async function render(){if(!['admin','employee'].includes(role()))return;try{const [s,m]=await Promise.all([rest('vendor_shipping_summary?select=*&order=vendor_code.asc'),rest('monthly_shipping_summary?select=*&order=month.desc,vendor_code.asc')]);header('vendorReportRows','已出貨');header('monthlyReportRows','已出貨');if($('vendorReportRows'))$('vendorReportRows').innerHTML=(s||[]).map(x=>`<tr><td><b>${esc(x.vendor_code)} ${esc(x.vendor_name)}</b></td><td>${Number(x.total_orders||0)}</td><td>${Number(x.open_orders||0)}</td><td class="${Number(x.overdue_orders)>0?'kpi-bad':''}">${Number(x.overdue_orders||0)}</td><td class="${Number(x.due_soon_orders)>0?'kpi-warn':''}">${Number(x.due_soon_orders||0)}</td><td>${Number(x.shipped_orders||0)}</td><td><b>${Number(x.shipped_boxes||0)} 箱</b></td><td class="${Number(x.on_time_rate)>=90?'kpi-good':''}">${x.on_time_rate==null?'—':`${x.on_time_rate}%`}</td><td>${x.avg_delay_days==null?'—':`${x.avg_delay_days} 天`}</td></tr>`).join('')||'<tr><td colspan="9">尚無資料</td></tr>';if($('monthlyReportRows'))$('monthlyReportRows').innerHTML=(m||[]).map(x=>`<tr><td>${esc(x.month)}</td><td>${esc(x.vendor_code)} ${esc(x.vendor_name)}</td><td>${Number(x.orders||0)}</td><td>${Number(x.shipped||0)}</td><td><b>${Number(x.shipped_boxes||0)} 箱</b></td><td>${Number(x.pending||0)}</td><td>${Number(x.on_time||0)}</td><td class="${Number(x.late)>0?'kpi-bad':''}">${Number(x.late||0)}</td><td>${x.on_time_rate==null?'—':`${x.on_time_rate}%`}</td></tr>`).join('')||'<tr><td colspan="9">尚無資料</td></tr>'}catch(e){console.warn('shipping report enhancement failed',e.message)}}
  window.addEventListener('DOMContentLoaded',()=>{document.addEventListener('click',e=>{if(e.target.closest?.('.tab[data-tab="report"]')){setTimeout(render,250);setTimeout(render,700)}})});
})();
